<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GestaoOS.Application</RootNamespace>
    <AssemblyName>GestaoOS.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GestaoOS.Domain\GestaoOS.Domain.csproj" />
  </ItemGroup>
</Project>
